### ISSUE TITLE
redirect to .aspx ?

### ISSUE THREAD

**Issue by knarfoe** [kaimallea/isMobile#28]
Hello,

This is my code:
  var MOBILE_SITE = '/mobile/mobile.aspx', // site to redirect to
                NO_REDIRECT = 'noredirect'; // cookie to prevent redirect

The redirect translates into:
..../mobile/index.html  instead of ../mobile/mobile.aspx

Any thoughts?
tnx
frank

**Comment by kaimallea** [comment]
Hi, this sounds like a back-end issue, and not an issue with the isMobile library itself.

What happens if you manually type `document.location = '/mobile/mobile.aspx';` in your JS console? Do you get the expected result? Also, try using the full address, e.g. `http://www.something.com/mobile/mobile.aspx`.
